"""initial schema

Revision ID: 33b530b3a818
Revises: 
Create Date: 2026-09-04 14:06:08.540325+00:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '33b530b3a818'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_channel_id'), 'conversations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_conversations_guild_id'), 'conversations', ['guild_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_guild_id'), 'credentials', ['guild_id'], unique=False)
    op.create_index(op.f('ix_credentials_provider'), 'credentials', ['provider'], unique=False)
    op.create_table('custom_commands',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('ai_powered', sa.Boolean(), nullable=False),
    sa.Column('alias_of', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_roles', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_commands_guild_id'), 'custom_commands', ['guild_id'], unique=False)
    op.create_index(op.f('ix_custom_commands_name'), 'custom_commands', ['name'], unique=False)
    op.create_table('guild_preferences',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_name', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('personality_mode', sa.String(length=24), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('autonomous_replies', sa.Boolean(), nullable=False),
    sa.Column('moderation_enabled', sa.Boolean(), nullable=False),
    sa.Column('tools_enabled', sa.Boolean(), nullable=False),
    sa.Column('music_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_tokens_per_msg', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_preferences_guild_id'), 'guild_preferences', ['guild_id'], unique=True)
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_guild_topic', 'knowledge_records', ['guild_id', 'topic'], unique=False)
    op.create_index(op.f('ix_knowledge_records_guild_id'), 'knowledge_records', ['guild_id'], unique=False)
    op.create_index(op.f('ix_knowledge_records_owner_user_id'), 'knowledge_records', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_records_topic'), 'knowledge_records', ['topic'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=True),
    sa.Column('source_author_id', sa.BigInteger(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_guild_id'), 'memories', ['guild_id'], unique=False)
    op.create_index(op.f('ix_memories_owner_user_id'), 'memories', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_memories_scope'), 'memories', ['scope'], unique=False)
    op.create_table('moderation_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_records_guild_id'), 'moderation_records', ['guild_id'], unique=False)
    op.create_table('provider_configs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_configs_guild_id'), 'provider_configs', ['guild_id'], unique=True)
    op.create_table('reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recurrence', sa.String(length=255), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('times_fired', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_due_at'), 'reminders', ['due_at'], unique=False)
    op.create_index(op.f('ix_reminders_guild_id'), 'reminders', ['guild_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('usage_stats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_stats_day'), 'usage_stats', ['day'], unique=False)
    op.create_index(op.f('ix_usage_stats_guild_id'), 'usage_stats', ['guild_id'], unique=False)
    op.create_index(op.f('ix_usage_stats_user_id'), 'usage_stats', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('personality_mode', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_guild_id'), 'channels', ['guild_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_pref')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_channels_guild_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_stats_user_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_guild_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_day'), table_name='usage_stats')
    op.drop_table('usage_stats')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_guild_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_provider_configs_guild_id'), table_name='provider_configs')
    op.drop_table('provider_configs')
    op.drop_index(op.f('ix_moderation_records_guild_id'), table_name='moderation_records')
    op.drop_table('moderation_records')
    op.drop_index(op.f('ix_memories_scope'), table_name='memories')
    op.drop_index(op.f('ix_memories_owner_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_guild_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_knowledge_records_topic'), table_name='knowledge_records')
    op.drop_index(op.f('ix_knowledge_records_owner_user_id'), table_name='knowledge_records')
    op.drop_index(op.f('ix_knowledge_records_guild_id'), table_name='knowledge_records')
    op.drop_index('ix_knowledge_guild_topic', table_name='knowledge_records')
    op.drop_table('knowledge_records')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_guild_preferences_guild_id'), table_name='guild_preferences')
    op.drop_table('guild_preferences')
    op.drop_index(op.f('ix_custom_commands_name'), table_name='custom_commands')
    op.drop_index(op.f('ix_custom_commands_guild_id'), table_name='custom_commands')
    op.drop_table('custom_commands')
    op.drop_index(op.f('ix_credentials_provider'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_guild_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_guild_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
